# application
VERSION: 0.0.1
HOST: 127.0.0.1:5000
SECRET_KEY: secret
DB_PASSWORD: user
TEST_ENV: false
PROD: false
DEBUG: false
AUTO_AUTHENTICATION: true
# database
DB_HOST: localhost
DB_PORT: 5432
DB_NAME: app
DB_USER: user
# services
EMAIL_SERVICE_HOST: 127.0.0.1:5001