VERSION: 0.0.1
HOST: 127.0.0.1:5000
DB_HOST: localhost
DB_PORT: 5432
DB_NAME: app
DB_USER: user
SECRET_KEY: secret
RESTORE_EMAIL_KEY: secret
DB_PASSWORD: user
PROD: false
DEBUG: false
EMAIL_SERVICE_HOST: 127.0.0.1:5001